new Schema('create_bic_bit:deep_frying')
    .simpleKey('results', 'outputFluidOrItemArray')
    .simpleKey('ingredients', 'inputFluidOrItemArray')
    .simpleKey('processingTime', 'doubleNumber')
    .simpleKey('heatRequirement', 'nonEmptyString')